//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRentalRecord
    {
        public int RentalId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> RentalDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> TypeOfCarId { get; set; }
    
        public virtual CarType CarType { get; set; }
    }
}
